### ISSUE TITLE
Request for fix: False postives on the AvoidUnguardedAssignmentToNonFinalFieldsInSharedObjects

### ISSUE THREAD

**Issue by peterschuler** [jborgers/PMD-jPinpoint-rules#99]
The AvoidUnguardedAssignmentToNonFinalFieldsInSharedObjects is now reporting issue with local method variables. This is clearly an error.

<img width="1782" alt="image" src="https://user-images.githubusercontent.com/5932617/101534939-2a27dd80-3998-11eb-8659-17a4704ee9a9.png">

This is already dicussed with @jborgers and an example file has been send in.

**Comment by jborgers** [comment]
Similar to #94

**Comment by jborgers** [comment]
Analysis:
It seems this is caused by solving the deprecation warnings concerning @Image to @Name, showing since 6.20 or so. 
For maven it is solved with the new maven-pmd-plugin, see #94 
Sonar (sonar-pmd-plugin) uses an old pmd (lastest, version 3.2.1 is from April 15, 2019) uses pmd 6.10. Newest is 6.29.
I tried to contact the owner of sonar-pmd-plugin, @jensgerdes, so far without luck.

**Comment by jborgers** [comment]
I forked to https://github.com/jborgers/sonar-pmd and fixed it there.
I tested sonar-pmd-plugin with my fixes in my local sonar 7.9 and it works, now more violations are showing!

**Comment by jborgers** [comment]
I created a PR. Tested OK in Sonar 8, too.

**Comment by jensgerdes** [comment]
Hi @jborgers

Thanks for the PR. I will check it within the next days. :-)

**Comment by jborgers** [comment]
That is very good news @jensgerdes

**Comment by peterschuler** [comment]
Thanks @jborgers and @jensgerdes for your work on this.

**Comment by jborgers** [comment]
sonar-pmd-plugin-3.3.0 seems to have an issue on Windows with the Windows file path. 
version 3.3.1 should fix that

**Comment by jborgers** [comment]
We used a pmd-plugin-3.3.1-snapshot which did not have the fix for the Windows/opaque issue. 
Now we use current snapshot and tester says YES on both Windows and Linux!
